import Head from 'next/head';
import { HomePage } from '@/src/components/home/home-page';

export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='home-page'>
        <HomePage data={ data } />
      </div>
    </div>
  )
}

//getServerSideProps is the function we use on NextJs to pass dynamic information, like APIs, to our page. 
export async function getServerSideProps() {
  const { events_categories } = await import('/data/data.json')  
  console.log(events_categories)
  return {
        props: {
          data: events_categories
        }
    }
}
